#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_QLBQA_csdl")]
public partial class dbcsdlDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttb_DanhMuc(tb_DanhMuc instance);
  partial void Updatetb_DanhMuc(tb_DanhMuc instance);
  partial void Deletetb_DanhMuc(tb_DanhMuc instance);
  partial void Inserttb_SanPhamChiTiet(tb_SanPhamChiTiet instance);
  partial void Updatetb_SanPhamChiTiet(tb_SanPhamChiTiet instance);
  partial void Deletetb_SanPhamChiTiet(tb_SanPhamChiTiet instance);
  partial void Inserttb_SanPham(tb_SanPham instance);
  partial void Updatetb_SanPham(tb_SanPham instance);
  partial void Deletetb_SanPham(tb_SanPham instance);
  #endregion
	
	public dbcsdlDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_QLBQA_csdlConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_DanhMuc> tb_DanhMucs
	{
		get
		{
			return this.GetTable<tb_DanhMuc>();
		}
	}
	
	public System.Data.Linq.Table<tb_SanPhamChiTiet> tb_SanPhamChiTiets
	{
		get
		{
			return this.GetTable<tb_SanPhamChiTiet>();
		}
	}
	
	public System.Data.Linq.Table<tb_SanPham> tb_SanPhams
	{
		get
		{
			return this.GetTable<tb_SanPham>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_DanhMuc")]
public partial class tb_DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dm_id;
	
	private string _dm_sp;
	
	private EntitySet<tb_SanPhamChiTiet> _tb_SanPhamChiTiets;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondm_idChanging(int value);
    partial void Ondm_idChanged();
    partial void Ondm_spChanging(string value);
    partial void Ondm_spChanged();
    #endregion
	
	public tb_DanhMuc()
	{
		this._tb_SanPhamChiTiets = new EntitySet<tb_SanPhamChiTiet>(new Action<tb_SanPhamChiTiet>(this.attach_tb_SanPhamChiTiets), new Action<tb_SanPhamChiTiet>(this.detach_tb_SanPhamChiTiets));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dm_id
	{
		get
		{
			return this._dm_id;
		}
		set
		{
			if ((this._dm_id != value))
			{
				this.Ondm_idChanging(value);
				this.SendPropertyChanging();
				this._dm_id = value;
				this.SendPropertyChanged("dm_id");
				this.Ondm_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_sp", DbType="NVarChar(MAX)")]
	public string dm_sp
	{
		get
		{
			return this._dm_sp;
		}
		set
		{
			if ((this._dm_sp != value))
			{
				this.Ondm_spChanging(value);
				this.SendPropertyChanging();
				this._dm_sp = value;
				this.SendPropertyChanged("dm_sp");
				this.Ondm_spChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_DanhMuc_tb_SanPhamChiTiet", Storage="_tb_SanPhamChiTiets", ThisKey="dm_id", OtherKey="dm_id")]
	public EntitySet<tb_SanPhamChiTiet> tb_SanPhamChiTiets
	{
		get
		{
			return this._tb_SanPhamChiTiets;
		}
		set
		{
			this._tb_SanPhamChiTiets.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_SanPhamChiTiets(tb_SanPhamChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.tb_DanhMuc = this;
	}
	
	private void detach_tb_SanPhamChiTiets(tb_SanPhamChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.tb_DanhMuc = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SanPhamChiTiet")]
public partial class tb_SanPhamChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _spct_id;
	
	private string _spct_name;
	
	private string _spct_image;
	
	private string _spct_giathanh;
	
	private System.Nullable<int> _dm_id;
	
	private System.Nullable<int> _sp_id;
	
	private EntityRef<tb_DanhMuc> _tb_DanhMuc;
	
	private EntityRef<tb_SanPham> _tb_SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onspct_idChanging(int value);
    partial void Onspct_idChanged();
    partial void Onspct_nameChanging(string value);
    partial void Onspct_nameChanged();
    partial void Onspct_imageChanging(string value);
    partial void Onspct_imageChanged();
    partial void Onspct_giathanhChanging(string value);
    partial void Onspct_giathanhChanged();
    partial void Ondm_idChanging(System.Nullable<int> value);
    partial void Ondm_idChanged();
    partial void Onsp_idChanging(System.Nullable<int> value);
    partial void Onsp_idChanged();
    #endregion
	
	public tb_SanPhamChiTiet()
	{
		this._tb_DanhMuc = default(EntityRef<tb_DanhMuc>);
		this._tb_SanPham = default(EntityRef<tb_SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int spct_id
	{
		get
		{
			return this._spct_id;
		}
		set
		{
			if ((this._spct_id != value))
			{
				this.Onspct_idChanging(value);
				this.SendPropertyChanging();
				this._spct_id = value;
				this.SendPropertyChanged("spct_id");
				this.Onspct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_name", DbType="NVarChar(MAX)")]
	public string spct_name
	{
		get
		{
			return this._spct_name;
		}
		set
		{
			if ((this._spct_name != value))
			{
				this.Onspct_nameChanging(value);
				this.SendPropertyChanging();
				this._spct_name = value;
				this.SendPropertyChanged("spct_name");
				this.Onspct_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_image", DbType="NVarChar(MAX)")]
	public string spct_image
	{
		get
		{
			return this._spct_image;
		}
		set
		{
			if ((this._spct_image != value))
			{
				this.Onspct_imageChanging(value);
				this.SendPropertyChanging();
				this._spct_image = value;
				this.SendPropertyChanged("spct_image");
				this.Onspct_imageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spct_giathanh", DbType="NVarChar(MAX)")]
	public string spct_giathanh
	{
		get
		{
			return this._spct_giathanh;
		}
		set
		{
			if ((this._spct_giathanh != value))
			{
				this.Onspct_giathanhChanging(value);
				this.SendPropertyChanging();
				this._spct_giathanh = value;
				this.SendPropertyChanged("spct_giathanh");
				this.Onspct_giathanhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dm_id", DbType="Int")]
	public System.Nullable<int> dm_id
	{
		get
		{
			return this._dm_id;
		}
		set
		{
			if ((this._dm_id != value))
			{
				if (this._tb_DanhMuc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondm_idChanging(value);
				this.SendPropertyChanging();
				this._dm_id = value;
				this.SendPropertyChanged("dm_id");
				this.Ondm_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_id", DbType="Int")]
	public System.Nullable<int> sp_id
	{
		get
		{
			return this._sp_id;
		}
		set
		{
			if ((this._sp_id != value))
			{
				if (this._tb_SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onsp_idChanging(value);
				this.SendPropertyChanging();
				this._sp_id = value;
				this.SendPropertyChanged("sp_id");
				this.Onsp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_DanhMuc_tb_SanPhamChiTiet", Storage="_tb_DanhMuc", ThisKey="dm_id", OtherKey="dm_id", IsForeignKey=true)]
	public tb_DanhMuc tb_DanhMuc
	{
		get
		{
			return this._tb_DanhMuc.Entity;
		}
		set
		{
			tb_DanhMuc previousValue = this._tb_DanhMuc.Entity;
			if (((previousValue != value) 
						|| (this._tb_DanhMuc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_DanhMuc.Entity = null;
					previousValue.tb_SanPhamChiTiets.Remove(this);
				}
				this._tb_DanhMuc.Entity = value;
				if ((value != null))
				{
					value.tb_SanPhamChiTiets.Add(this);
					this._dm_id = value.dm_id;
				}
				else
				{
					this._dm_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_DanhMuc");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_SanPhamChiTiet", Storage="_tb_SanPham", ThisKey="sp_id", OtherKey="sp_id", IsForeignKey=true)]
	public tb_SanPham tb_SanPham
	{
		get
		{
			return this._tb_SanPham.Entity;
		}
		set
		{
			tb_SanPham previousValue = this._tb_SanPham.Entity;
			if (((previousValue != value) 
						|| (this._tb_SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_SanPham.Entity = null;
					previousValue.tb_SanPhamChiTiets.Remove(this);
				}
				this._tb_SanPham.Entity = value;
				if ((value != null))
				{
					value.tb_SanPhamChiTiets.Add(this);
					this._sp_id = value.sp_id;
				}
				else
				{
					this._sp_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("tb_SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_SanPham")]
public partial class tb_SanPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sp_id;
	
	private string _sp_name;
	
	private EntitySet<tb_SanPhamChiTiet> _tb_SanPhamChiTiets;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsp_idChanging(int value);
    partial void Onsp_idChanged();
    partial void Onsp_nameChanging(string value);
    partial void Onsp_nameChanged();
    #endregion
	
	public tb_SanPham()
	{
		this._tb_SanPhamChiTiets = new EntitySet<tb_SanPhamChiTiet>(new Action<tb_SanPhamChiTiet>(this.attach_tb_SanPhamChiTiets), new Action<tb_SanPhamChiTiet>(this.detach_tb_SanPhamChiTiets));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sp_id
	{
		get
		{
			return this._sp_id;
		}
		set
		{
			if ((this._sp_id != value))
			{
				this.Onsp_idChanging(value);
				this.SendPropertyChanging();
				this._sp_id = value;
				this.SendPropertyChanged("sp_id");
				this.Onsp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp_name", DbType="NVarChar(MAX)")]
	public string sp_name
	{
		get
		{
			return this._sp_name;
		}
		set
		{
			if ((this._sp_name != value))
			{
				this.Onsp_nameChanging(value);
				this.SendPropertyChanging();
				this._sp_name = value;
				this.SendPropertyChanged("sp_name");
				this.Onsp_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_SanPham_tb_SanPhamChiTiet", Storage="_tb_SanPhamChiTiets", ThisKey="sp_id", OtherKey="sp_id")]
	public EntitySet<tb_SanPhamChiTiet> tb_SanPhamChiTiets
	{
		get
		{
			return this._tb_SanPhamChiTiets;
		}
		set
		{
			this._tb_SanPhamChiTiets.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_SanPhamChiTiets(tb_SanPhamChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.tb_SanPham = this;
	}
	
	private void detach_tb_SanPhamChiTiets(tb_SanPhamChiTiet entity)
	{
		this.SendPropertyChanging();
		entity.tb_SanPham = null;
	}
}
#pragma warning restore 1591
