<?xml version="1.0" encoding="utf-8"?><Database Name="db_QLBQA_csdl" Class="dbcsdlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-LM2PA7D\SQLEXPRESS;Initial Catalog=db_QLBQA_csdl;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_QLBQA_csdlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_DanhMuc" Member="tb_DanhMucs">
    <Type Name="tb_DanhMuc">
      <Column Name="dm_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dm_sp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tb_DanhMuc_tb_SanPhamChiTiet" Member="tb_SanPhamChiTiets" ThisKey="dm_id" OtherKey="dm_id" Type="tb_SanPhamChiTiet" />
    </Type>
  </Table>
  <Table Name="dbo.tb_SanPhamChiTiet" Member="tb_SanPhamChiTiets">
    <Type Name="tb_SanPhamChiTiet">
      <Column Name="spct_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="spct_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="spct_image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="spct_giathanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dm_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sp_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_DanhMuc_tb_SanPhamChiTiet" Member="tb_DanhMuc" ThisKey="dm_id" OtherKey="dm_id" Type="tb_DanhMuc" IsForeignKey="true" />
      <Association Name="tb_SanPham_tb_SanPhamChiTiet" Member="tb_SanPham" ThisKey="sp_id" OtherKey="sp_id" Type="tb_SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_SanPham" Member="tb_SanPhams">
    <Type Name="tb_SanPham">
      <Column Name="sp_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sp_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tb_SanPham_tb_SanPhamChiTiet" Member="tb_SanPhamChiTiets" ThisKey="sp_id" OtherKey="sp_id" Type="tb_SanPhamChiTiet" />
    </Type>
  </Table>
</Database>